name: Apple build
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
paths:
  - apple/**

jobs:
  gradlew-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install Java
        uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '21'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: |
          cd apple
          chmod +x gradlew
          ./gradlew build
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gradle dist
          path: |
            apple/app/build/distributions
      - run: echo "ğŸ This job's status is ${{ job.status }}."
